spring:
  datasource:
    url: jdbc:h2:file:./data/newsreporterstore
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
app:
  base:
    url: http://localhost:8080
  reports:
    dir: reports

#  web:
#    resources:
#      static-locations: file:./files/
#  mvc:
#    log-request-details: true
#logging:
#  level:
#    reactor:
#      netty:
#        http:
#          client=debug:
#logging.level.org.springframework.web: DEBUG
#debug: true

