INSERT INTO PUBLIC.news (DATE, URL, NAME, BODY)
VALUES (CURRENT_TIMESTAMP, 'http://test.com', 'TESTNAME', '<HTML><BODY></BODY></HTML>');
INSERT INTO PUBLIC.news (DATE, URL, NAME, BODY)
VALUES (CURRENT_TIMESTAMP, 'http://test1.com', 'TESTNAME1', '<HTML><BODY></BODY></HTML>');
